api_platform:
    title: Eval GAMES du 17/02/2026
    formats:
        json: ['application/json']
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
